name: CD

on:
  push:
    branches:
      - master
 
jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
     - name: CheckOut
       uses: actions/checkout@v2
       with:
        repository: workout-log/back-end
   
     - name: Chmod
       run: |
        ls
        chmod 777 deployment.sh
        
     - name: Delpoy to ec2
       uses: appleboy/ssh-action@master
       with:
         USERNAME: ${{ secrets.EC2_USERNAME }}
         HOST: ${{ secrets.EC2_HOST }}
         KEY: ${{ secrets.SSH_DEPLOYMENT_KEY }}
         script: |
           cd back-end
           git pull
           docker pull woochanlee/workoutlog
           docker-compose up -d
